name: tidy
on:
  pull_request:
    paths:
      - ".github/workflows/gosum.yml"
      - "go.mod"
      - "go.sum"

jobs:
  tidy:
    name: run go mod tidy and updated
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: reattach HEAD to Head Ref
        # b/c checkout action leaves in detached head state https://github.com/actions/checkout/issues/6
        run: git checkout "$(echo ${{ github.head_ref }})"
        if: github.head_ref != ''
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - name: Tidy
        run: |
          go version
          go mod tidy
      - name: set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: commit and push changes
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'Fix go modules'
            git push
          fi
